import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Container from "@/components/layout";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={GeistSans.className}>
        <ThemeProvider attribute="class">
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
